# Constants for colors
RED = "\033[31m"
RESET = "\033[0m"
GREEN = "\033[32m"
ORANGE = "\033[38;5;208m"
PURPLE = "\033[38;5;129m"

# Constants for piece types
EMPTY = "-"
ORANGE_PIECE = "0"
GREEN_PIECE = "O"
ORANGE_QUEEN = "K"
GREEN_QUEEN = "Q"

# Constants for player numbers
PLAYER_ORANGE = "2"
PLAYER_GREEN = "1"

# Enums for pieces
ENUM_NORMAL = {PLAYER_ORANGE: ORANGE_PIECE, PLAYER_GREEN: GREEN_PIECE}
ENUM_PROMOTED = {PLAYER_ORANGE: ORANGE_QUEEN, PLAYER_GREEN: GREEN_QUEEN}
ENUM_COLORS = {PLAYER_GREEN: GREEN, PLAYER_ORANGE: ORANGE}

OPOSITES = {PLAYER_ORANGE: set([GREEN_PIECE, GREEN_QUEEN]), PLAYER_GREEN: set([
    ORANGE_PIECE, ORANGE_QUEEN])}
